apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extrcatdata-pvc
  namespace: vitalwayai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: extrcatdata-replicaset
  namespace: vitalwayai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extrcatdata
  template:
    metadata:
      namespace: vitalwayai
      labels:
        app: extrcatdata
    spec:
      containers:
      - name: extrcatdata
        image: ghcr.io/vitalway-eng/vitalaipipeline:1.0
        imagePullPolicy: Always
        env:
          - name: EXEC_MODE
            value: "PUSH"
          - name: SRC_FOLDER
            value: "/data"
          - name: REDIS_HOST
            value: "192.168.8.54"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: "Vtw123$%^"
          - name: REDIS_USERNAME
            value: "default"
        volumeMounts:
        - name: storage-volume
          mountPath: /data
      imagePullSecrets:
      - name: github-registry-pull-secret
      hostAliases:
      - ip: "192.168.8.54"
        hostnames:
        - "gx10-3fe2"
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: extrcatdata-pvc
