apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infereollama-pvc
  namespace: vitalwayai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: infereollama-replicaset
  namespace: vitalwayai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infereollama
  template:
    metadata:
      namespace: vitalwayai
      labels:
        app: infereollama
    spec:
      nodeName: gx10-3fe2
      hostNetwork: true
      containers:
      - name: infereollama
        image: ghcr.io/vitalway-eng/vitalaiollama:1.0
        imagePullPolicy: Always
        env:
          - name: DATABASE_HOST
            value: "192.168.8.55"
          - name: DATABASE_USER
            value: "dbuser"
          - name: DATABASE_PASS 
            value: "Vtw123$%^"
          - name: DATABASE_NAME
            value: "customerdb"
          - name: OLLAMA_HOST
            value: "192.168.8.54"
          - name: OLLAMA_MODEL
            value: "gpt-oss:20b"
          - name: REDIS_HOST
            value: "192.168.8.54"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: "Vtw123$%^"
          - name: REDIS_USERNAME
            value: "default"
          - name: TIKTOKEN_CACHE_DIR
            value: "/app/tiktoken_cache/"
          - name: TIKTOKEN_FILE
            value: "cl100k_base.tiktoken"
          - name: "CREWAI_DISABLE_TELEMETRY"
            value: "true"
        resources:
          requests:
            cpu: "5"      # Guaranteed baseline allocation (e.g., 5 cores)
            memory: "4Gi"
          limits:
            cpu: "8"      # Hard ceiling: Cannot burst past 6 CPUs
            memory: "8Gi"
        volumeMounts:
        - name: storage-volume
          mountPath: /data
      imagePullSecrets:
      - name: github-registry-pull-secret
      hostAliases:
      - ip: "192.168.8.54"
        hostnames:
        - "gx10-3fe2"
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: infereollama-pvc
