apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: vitalwayai
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  externalIPs:
    - 192.168.8.54
  selector:
    app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: vitalwayai
type: Opaque
stringData:
  ROOT_PASSWORD: "Vtw123$%^" # Change this!
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: vitalwayai
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
        namespace: vitalwayai
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn-redis-storage"
        resources:
          requests:
            storage: 10Gi # Adjust size based on your database needs

